image: maven:3.6.0-jdk-8

test: 
  stage: test
  when: always
  script: 
    - mvn clean compile
  tags: 
    - gitlab-org
  retry: 
    max: 2
    when: always
  cache:
    paths:
      - .m2/repository

build: 
  stage: build
  when: on_success
  script: 
    - mvn package
  artifacts:
    paths:
      - target/*.jar
  only: 
      - master
  