image: maven:3.6.0-jdk-8

stages:
  - test
  - build

test: 
  stage: test
  when: always
  only: 
    - master
  script: 
    - mvn clean compile
  tags: 
    - gitlab-org
  retry: 
    max: 2
    when: always
  cache:
    paths:
      - ~/.m2/repository

build: 
  stage: build
  when: on_success
  only: 
    - master
  script: 
    - mvn clean package
  tags: 
    - gitlab-org
  cache:
    paths:
      - ~/.m2/repository
  artifacts:
    paths:
      - target/*.jar
  