image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
   - docker info

stages:
  - mvn_build
  - docker_build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
    key: "$CI_JOB_NAME"
    paths:
      - .m2/

mvn_build: 
  image: maven:3.6.0-jdk-8-slim
  stage: mvn_build
  only: 
    - master
  script: 
    - mvn clean package
    - mkdir -p /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    - cp target/app.jar /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/app.jar
    - cp src/main/docker/Dockerfile /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/Dockerfile
  tags: 
    - docker-executor

docker_build: 
  when: on_success 
  stage: docker_build
  only: 
    - master
  script: 
    - cd /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/
    - docker build -t ${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}:${CI_COMMIT_SHA} .
  tags: 
    - docker-executor



  