image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

stages:
  - test
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay

cache:
    key: "$CI_JOB_NAME"
    paths:
      - .m2/

build: 
  stage: build
  when: on_success
  only: 
    - master
  script: 
    - mvn clean package
    - ls -a
    - mkdir -p /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    - cp target/app.jar /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/app.jar
    - cp src/main/docker/Dockerfile /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/Dockerfile
    - cd /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/
    - pwd
    - docker build -t ${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}:${CI_COMMIT_SHA} .
  tags: 
    - my-gitlab-ci



  