image: maven:3-jdk-8-slim

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

stages:
  - mvn_test

cache:
    key: "$CI_PROJECT_ID"
    paths:
      - .m2/

mvn_build:
  stage: mvn_test
  only: 
    - master
  script: 
    - mvn clean package
  tags: 
    - docker-executor
