image: maven:3.6.0-jdk-8

stages:
  - test
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

test: 
  stage: test
  when: always
  only: 
    - master
  script: 
    - mvn clean compile
  tags: 
    - gitlab-org
  retry: 
    max: 2
    when: always
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - ./.m2/repository/

build: 
  stage: build
  when: on_success
  only: 
    - master
  script: 
    - mvn clean package
  tags: 
    - gitlab-org
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - ./.m2/repository/
  artifacts:
    paths:
      - target/*.jar
  