image: maven:3.6.0-jdk-8

stages:
  - test
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"
cache:
    key: "$CI_JOB_NAME"
    paths:
      - .m2/

test: 
  stage: test
  when: always
  only: 
    - master
  script: 
    - mvn clean compile
  tags: 
    - gitlab-org
  retry: 
    max: 2
    when: always

build: 
  stage: build
  when: on_success
  only: 
    - master
  script: 
    - *.test_success
  tags: 
    - gitlab-org

.test_success: &.test_success |
  curl -X GET \
  'http://122.194.3.103:9090/build?isSuccess=true&repoUrl=${CI_PROJECT_URL}'

  