image: maven:3.6.0-jdk-8

stages:
  - test
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=cache/.m2"
cache:
    key: "$CI_JOB_NAME"
    paths:
      - cache/.m2/repository/

test: 
  stage: test
  when: always
  only: 
    - master
  script: 
    - mvn clean compile
  tags: 
    - gitlab-org
  retry: 
    max: 2
    when: always

build: 
  stage: build
  when: on_success
  only: 
    - master
  script: 
    - mvn clean package
  tags: 
    - gitlab-org
  artifacts:
    paths:
      - target/*.jar
  