image: maven:3.6.0-jdk-8

stages:
  - test
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"
cache:
    key: "$CI_JOB_NAME"
    paths:
      - .m2/

test: 
  stage: test
  when: always
  only: 
    - master
  script: 
    - mvn clean compile
  tags: 
    - my-gitlab-ci
  retry: 
    max: 2
    when: always
    
.test_success: &test_success |
  echo "build success!"

build: 
  stage: build
  when: on_success
  only: 
    - master
  script: 
    - *test_success
  tags: 
    - my-gitlab-ci



  